# Generated by Django 4.0.5 on 2022-07-28 15:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Directorate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.DecimalField(decimal_places=3, max_digits=7)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("time", models.IntegerField(blank=True, null=True)),
                ("division", models.IntegerField(blank=True, null=True)),
                ("contacts", models.IntegerField(blank=True, null=True)),
                ("his", models.CharField(blank=True, max_length=100, null=True)),
                ("inpatient", models.IntegerField(blank=True, null=True)),
                ("district", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "sub_district",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "fft_category",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "directorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.directorate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommentsCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comments_good",
                    models.TextField(blank=True, help_text="What was good?", null=True),
                ),
                (
                    "comments_better",
                    models.TextField(
                        blank=True, help_text="What could we do better?", null=True
                    ),
                ),
                (
                    "comments_public",
                    models.BooleanField(
                        blank=True,
                        help_text="Please tick here if you DO NOT wish your comments to be made public",
                        null=True,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.team"
                    ),
                ),
                ("criticality", models.PositiveIntegerField(blank=True, null=True)),
                ("positivity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "best_code_1",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"forms__name": "Person"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="best1",
                        to="web.commentscode",
                    ),
                ),
                (
                    "best_code_2",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"forms__name": "Person"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="best2",
                        to="web.commentscode",
                    ),
                ),
                (
                    "improve_code_1",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"forms__name": "Person"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="improve1",
                        to="web.commentscode",
                    ),
                ),
                (
                    "improve_code_2",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"forms__name": "Person"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="improve2",
                        to="web.commentscode",
                    ),
                ),
                (
                    "paper_index",
                    models.IntegerField(editable=False, null=True, unique=True),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["updated_at"],
                "permissions": [
                    ("add_response", "Can add new form responses"),
                    ("update_response", "Can update form responses"),
                    ("code_response", "Can code forms based on comments"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FormResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("adult", "Adult"),
                            ("child", "Child"),
                            ("carer", "Carer"),
                            ("young carer", "Young Carer"),
                            ("accessible", "Accessible"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accessible",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.person",
                    ),
                ),
                (
                    "ask",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did our staff ask you what you wanted?",
                        limit_choices_to={"forms__name": "Accessible", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessible_ask",
                        to="web.rating",
                    ),
                ),
                (
                    "better",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did our staff help you feel better?",
                        limit_choices_to={"forms__name": "Accessible", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessible_better",
                        to="web.rating",
                    ),
                ),
                (
                    "carer_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="I am a: ",
                        limit_choices_to={"forms__name": "Accessible", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.serviceuser",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did you have a good experience from our staff?",
                        limit_choices_to={"forms__name": "Accessible", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessible_experience",
                        to="web.rating",
                    ),
                ),
                (
                    "explaining",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did our staff explain things clearly?",
                        limit_choices_to={"forms__name": "Accessible", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessible_explaining",
                        to="web.rating",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        blank=True,
                        help_text="Were our staff kind to you?",
                        limit_choices_to={"forms__name": "Accessible", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessible_kind",
                        to="web.rating",
                    ),
                ),
                (
                    "listening",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did our staff listen to you?",
                        limit_choices_to={"forms__name": "Accessible", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessible_listening",
                        to="web.rating",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("web.person",),
        ),
        migrations.CreateModel(
            name="Age",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarerType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="commentscode",
            name="forms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which forms the response should be displayed on",
                to="web.formresponses",
            ),
        ),
        migrations.CreateModel(
            name="ContactGeneric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Disability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EthnicGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pregnant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="rating",
            name="forms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which forms the response should be displayed on",
                to="web.formresponses",
            ),
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="serviceuser",
            name="forms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which forms the response should be displayed on",
                to="web.formresponses",
            ),
        ),
        migrations.CreateModel(
            name="SexualOrientation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the field needs to be hidden on the form",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which forms the response should be displayed on",
                        to="web.formresponses",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Adult",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.person",
                    ),
                ),
                (
                    "age",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.age",
                    ),
                ),
                (
                    "baby",
                    models.ForeignKey(
                        blank=True,
                        help_text="Have you had a baby within the last 26 weeks?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baby",
                        to="web.pregnant",
                    ),
                ),
                (
                    "carer_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="I am a: ",
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.serviceuser",
                    ),
                ),
                (
                    "disability",
                    models.ForeignKey(
                        blank=True,
                        help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.disability",
                    ),
                ),
                (
                    "ethnic_group",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.ethnicgroup",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        help_text="Overall, how was your experience of our service?",
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experience",
                        to="web.rating",
                    ),
                ),
                (
                    "explaining",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at explaining information clearly?",
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="explaining",
                        to="web.rating",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.gender",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at being kind to you?",
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kind",
                        to="web.rating",
                    ),
                ),
                (
                    "listening",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at listening to you?",
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listening",
                        to="web.rating",
                    ),
                ),
                (
                    "positive",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at making a positive difference to your health and wellbeing?",
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positive",
                        to="web.rating",
                    ),
                ),
                (
                    "pregnant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Are you pregnant at this time?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pregnant",
                        to="web.pregnant",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        help_text="What is your relationship status?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.relationship",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.religion",
                    ),
                ),
                (
                    "sexual_orientation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.sexualorientation",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at involving you in decisions about your care or treatment?",
                        limit_choices_to={"forms__name": "Adult", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment",
                        to="web.rating",
                    ),
                ),
            ],
            bases=("web.person", models.Model),
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.person",
                    ),
                ),
                (
                    "carer_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="I am a: ",
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.serviceuser",
                    ),
                ),
                (
                    "disability",
                    models.ForeignKey(
                        blank=True,
                        help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.disability",
                    ),
                ),
                (
                    "ethnic_group",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.ethnicgroup",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        help_text="Overall, how was your experience of our service?",
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_experience",
                        to="web.rating",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.gender",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        help_text="What is your relationship status?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.relationship",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.religion",
                    ),
                ),
                (
                    "sexual_orientation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.sexualorientation",
                    ),
                ),
                (
                    "age",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.age",
                    ),
                ),
                (
                    "explaining",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at explaining information clearly?",
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_explaining",
                        to="web.rating",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at being kind to you?",
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_kind",
                        to="web.rating",
                    ),
                ),
                (
                    "listening",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at listening to you?",
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_listening",
                        to="web.rating",
                    ),
                ),
                (
                    "positive",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at making a positive difference to your health and wellbeing?",
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_positive",
                        to="web.rating",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at involving you in decisions about your care or treatment?",
                        limit_choices_to={"forms__name": "Child", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_treatment",
                        to="web.rating",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("web.person",),
        ),
        migrations.CreateModel(
            name="YoungCarer",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.person",
                    ),
                ),
                (
                    "age",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.age",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did we tell you who to contact for a carers assessment?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_assessment",
                        to="web.rating",
                    ),
                ),
                (
                    "disability",
                    models.ForeignKey(
                        blank=True,
                        help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.disability",
                    ),
                ),
                (
                    "ethnic_group",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.ethnicgroup",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        help_text="Overall, how was your experience of our service?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_experience",
                        to="web.rating",
                    ),
                ),
                (
                    "explaining",
                    models.ForeignKey(
                        blank=True,
                        help_text="Were our services good at explaining things clearly?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_explaining",
                        to="web.rating",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.gender",
                    ),
                ),
                (
                    "involving",
                    models.ForeignKey(
                        blank=True,
                        help_text="Were our services good at involving you in the way we helped the person you care for?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_involving",
                        to="web.rating",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        blank=True,
                        help_text="Were our services good at being kind to you?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_kind",
                        to="web.rating",
                    ),
                ),
                (
                    "listening",
                    models.ForeignKey(
                        blank=True,
                        help_text="Were our services good at listening to you?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_listening",
                        to="web.rating",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        help_text="What is your relationship status?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.relationship",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.religion",
                    ),
                ),
                (
                    "sexual_orientation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.sexualorientation",
                    ),
                ),
                (
                    "talking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Were our services good at talking to you about the support you could have as a carer?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_talking",
                        to="web.rating",
                    ),
                ),
                (
                    "worried",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did our services tell you who you could contact if you were worried about the person you care for?",
                        limit_choices_to={
                            "forms__name": "Young Carer",
                            "hidden": False,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="young_carer_worried",
                        to="web.rating",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("web.person",),
        ),
        migrations.AlterField(
            model_name="person",
            name="best_code_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="best1",
                to="web.commentscode",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="best_code_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="best2",
                to="web.commentscode",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="improve_code_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="improve1",
                to="web.commentscode",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="improve_code_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="improve2",
                to="web.commentscode",
            ),
        ),
        migrations.CreateModel(
            name="Carer",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.person",
                    ),
                ),
                (
                    "age",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.age",
                    ),
                ),
                (
                    "disability",
                    models.ForeignKey(
                        blank=True,
                        help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.disability",
                    ),
                ),
                (
                    "ethnic_group",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.ethnicgroup",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        help_text="Overall, how was your experience of our service?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_experience",
                        to="web.rating",
                    ),
                ),
                (
                    "explaining",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at explaining information clearly?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_explaining",
                        to="web.rating",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.gender",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at being kind to you?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_kind",
                        to="web.rating",
                    ),
                ),
                (
                    "listening",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at listening to you?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_listening",
                        to="web.rating",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        help_text="What is your relationship status?",
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.relationship",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.religion",
                    ),
                ),
                (
                    "sexual_orientation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.sexualorientation",
                    ),
                ),
                (
                    "support",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at giving you information about support for you as a carer?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_support",
                        to="web.rating",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        help_text="How good were our services at involving you in decisions about the care and treatment of the person you care for?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_treatment",
                        to="web.rating",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did we tell you who to contact for a carers assessment?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_assessment",
                        to="web.contactgeneric",
                    ),
                ),
                (
                    "carer_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="I am a carer, family member, friend, parent or guardian of someone:",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_type",
                        to="web.carertype",
                    ),
                ),
                (
                    "worried",
                    models.ForeignKey(
                        blank=True,
                        help_text="Did our services tell you who you could contact if you were worried about the person you care for?",
                        limit_choices_to={"forms__name": "Carer", "hidden": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carer_worried",
                        to="web.contactgeneric",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("web.person",),
        ),
    ]
