# Generated by Django 4.0.5 on 2022-06-29 13:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_commentscode_person_criticality_person_positivity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildAge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChildRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["updated_at"]},
        ),
        migrations.AddField(
            model_name="child",
            name="carer_type",
            field=models.ForeignKey(
                help_text="I am a: ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.serviceuser",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="disability",
            field=models.ForeignKey(
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="ethnic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="experience",
            field=models.ForeignKey(
                help_text="Overall, how was your experience of our service?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_experience",
                to="web.rating",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="gender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="web.gender"
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="relationship",
            field=models.ForeignKey(
                help_text="What is your relationship status?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="religion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="sexual_orientation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="age",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="web.age"
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="disability",
            field=models.ForeignKey(
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="ethnic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="gender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="web.gender"
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="relationship",
            field=models.ForeignKey(
                help_text="What is your relationship status?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="religion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="sexual_orientation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="age",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.childage",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="explaining",
            field=models.ForeignKey(
                help_text="How good were our services at explaining information clearly?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_explaining",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="kind",
            field=models.ForeignKey(
                help_text="How good were our services at being kind to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_kind",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="listening",
            field=models.ForeignKey(
                help_text="How good were our services at listening to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_listening",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="positive",
            field=models.ForeignKey(
                help_text="How good were our services at making a positive difference to your health and wellbeing?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_positive",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="treatment",
            field=models.ForeignKey(
                help_text="How good were our services at involving you in decisions about your care or treatment?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_treatment",
                to="web.childrating",
            ),
        ),
    ]
