# Generated by Django 4.0.5 on 2022-07-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_childage_childrating_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="youngcarer",
            name="age",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.childage",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="assessment",
            field=models.ForeignKey(
                help_text="Did we tell you who to contact for a carers’ assessment?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_assessment",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="disability",
            field=models.ForeignKey(
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="ethnic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="experience",
            field=models.ForeignKey(
                help_text="Overall, how was your experience of our service?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_experience",
                to="web.rating",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="explaining",
            field=models.ForeignKey(
                help_text="Were our services good at explaining things clearly?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_explaining",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="gender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="web.gender"
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="involving",
            field=models.ForeignKey(
                help_text="Were our services good at involving you in the way we helped the person you care for?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_involving",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="kind",
            field=models.ForeignKey(
                help_text="Were our services good at being kind to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_kind",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="listening",
            field=models.ForeignKey(
                help_text="Were our services good at listening to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_listening",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="relationship",
            field=models.ForeignKey(
                help_text="What is your relationship status?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="religion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="sexual_orientation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="talking",
            field=models.ForeignKey(
                help_text="Were our services good at talking to you about the support you could have as a carer?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_talking",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="youngcarer",
            name="worried",
            field=models.ForeignKey(
                help_text="Did our services tell you who you could contact if you were worried about the person you care for?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_worried",
                to="web.childrating",
            ),
        ),
    ]
