# Generated by Django 4.0.5 on 2022-07-04 13:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_youngcarer_age_youngcarer_assessment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarerType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactGeneric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carer",
            name="age",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="web.age"
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="disability",
            field=models.ForeignKey(
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="ethnic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="experience",
            field=models.ForeignKey(
                help_text="Overall, how was your experience of our service?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_experience",
                to="web.rating",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="explaining",
            field=models.ForeignKey(
                help_text="How good were our services at explaining information clearly?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_explaining",
                to="web.rating",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="gender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="web.gender"
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="kind",
            field=models.ForeignKey(
                help_text="How good were our services at being kind to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_kind",
                to="web.rating",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="listening",
            field=models.ForeignKey(
                help_text="How good were our services at listening to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_listening",
                to="web.rating",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="relationship",
            field=models.ForeignKey(
                help_text="What is your relationship status?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="religion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="sexual_orientation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="support",
            field=models.ForeignKey(
                help_text="How good were our services at giving you information about support for you as a carer?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_support",
                to="web.rating",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="treatment",
            field=models.ForeignKey(
                help_text="How good were our services at involving you in decisions about the care and treatment of the person you care for?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_treatment",
                to="web.rating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="assessment",
            field=models.ForeignKey(
                help_text="Did we tell you who to contact for a carers assessment?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_assessment",
                to="web.childrating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="experience",
            field=models.ForeignKey(
                help_text="Overall, how was your experience of our service?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_experience",
                to="web.rating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="explaining",
            field=models.ForeignKey(
                help_text="Were our services good at explaining things clearly?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_explaining",
                to="web.childrating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="involving",
            field=models.ForeignKey(
                help_text="Were our services good at involving you in the way we helped the person you care for?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_involving",
                to="web.childrating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="kind",
            field=models.ForeignKey(
                help_text="Were our services good at being kind to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_kind",
                to="web.childrating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="listening",
            field=models.ForeignKey(
                help_text="Were our services good at listening to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_listening",
                to="web.childrating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="talking",
            field=models.ForeignKey(
                help_text="Were our services good at talking to you about the support you could have as a carer?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_talking",
                to="web.childrating",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="worried",
            field=models.ForeignKey(
                help_text="Did our services tell you who you could contact if you were worried about the person you care for?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="young_carer_worried",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="assessment",
            field=models.ForeignKey(
                help_text="Did we tell you who to contact for a carers’ assessment?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_assessment",
                to="web.contactgeneric",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="carer_type",
            field=models.ForeignKey(
                help_text="I am a carer, family member, friend, parent or guardian of someone:",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_type",
                to="web.carertype",
            ),
        ),
        migrations.AddField(
            model_name="carer",
            name="worried",
            field=models.ForeignKey(
                help_text="Did our services tell you who you could contact if you were worried about the person you care for?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_worried",
                to="web.contactgeneric",
            ),
        ),
    ]
