# Generated by Django 4.0.5 on 2022-07-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_carertype_contactgeneric_carer_age_carer_disability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessible",
            name="ask",
            field=models.ForeignKey(
                help_text="Did our staff ask you what you wanted?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accessible_ask",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="accessible",
            name="better",
            field=models.ForeignKey(
                help_text="Did our staff help you feel better?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accessible_better",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="accessible",
            name="carer_type",
            field=models.ForeignKey(
                help_text="I am a: ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.serviceuser",
            ),
        ),
        migrations.AddField(
            model_name="accessible",
            name="experience",
            field=models.ForeignKey(
                help_text="Did you have a good experience from our staff?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accessible_experience",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="accessible",
            name="explaining",
            field=models.ForeignKey(
                help_text="Did our staff explain things clearly?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accessible_explaining",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="accessible",
            name="kind",
            field=models.ForeignKey(
                help_text="Were our staff kind to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accessible_kind",
                to="web.childrating",
            ),
        ),
        migrations.AddField(
            model_name="accessible",
            name="listening",
            field=models.ForeignKey(
                help_text="Did our staff listen to you?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accessible_listening",
                to="web.childrating",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="assessment",
            field=models.ForeignKey(
                help_text="Did we tell you who to contact for a carers assessment?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carer_assessment",
                to="web.contactgeneric",
            ),
        ),
    ]
