# Generated by Django 4.0.5 on 2022-07-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_accessible_ask_alter_accessible_better_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="age",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="carertype",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="childage",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="childrating",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="commentscode",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="contactgeneric",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="disability",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="ethnicgroup",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="gender",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="pregnant",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="religion",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="serviceuser",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
        migrations.AddField(
            model_name="sexualorientation",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Select if the field needs to be hidden on the form",
            ),
        ),
    ]
