# Generated by Django 4.0.5 on 2022-07-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_person_paper_index_alter_accessible_ask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="paper_index",
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
