# Generated by Django 4.0.5 on 2022-07-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_person_paper_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["updated_at"],
                "permissions": [
                    ("add_response", "Can add new form responses"),
                    ("update_response", "Can update form responses"),
                    ("code_response", "Can code forms based on comments"),
                ],
            },
        ),
    ]
