# Generated by Django 4.0.5 on 2022-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
