# Generated by Django 4.0.5 on 2022-07-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_formresponses_alter_accessible_ask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adult",
            name="baby",
            field=models.ForeignKey(
                blank=True,
                help_text="Have you had a baby within the last 26 weeks?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="baby",
                to="web.pregnant",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="disability",
            field=models.ForeignKey(
                blank=True,
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="ethnic_group",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.gender",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="pregnant",
            field=models.ForeignKey(
                blank=True,
                help_text="Are you pregnant at this time?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pregnant",
                to="web.pregnant",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                help_text="What is your relationship status?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="religion",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="sexual_orientation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="age",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.age",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="disability",
            field=models.ForeignKey(
                blank=True,
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="ethnic_group",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.gender",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                help_text="What is your relationship status?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="religion",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AlterField(
            model_name="carer",
            name="sexual_orientation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="disability",
            field=models.ForeignKey(
                blank=True,
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="ethnic_group",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.gender",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                help_text="What is your relationship status?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="religion",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="sexual_orientation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="disability",
            field=models.ForeignKey(
                blank=True,
                help_text="Do you have a long term disability or a long-term health condition which affects your day to day activities?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.disability",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="ethnic_group",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.ethnicgroup",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.gender",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                help_text="What is your relationship status?",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.relationship",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="religion",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.religion",
            ),
        ),
        migrations.AlterField(
            model_name="youngcarer",
            name="sexual_orientation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.sexualorientation",
            ),
        ),
    ]
