# Generated by Django 4.0.5 on 2022-07-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_alter_adult_baby_alter_adult_disability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="best_code_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="best1",
                to="web.commentscode",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="best_code_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="best2",
                to="web.commentscode",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="improve_code_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="improve1",
                to="web.commentscode",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="improve_code_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="improve2",
                to="web.commentscode",
            ),
        ),
    ]
